In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


a = np.arange(10)
print(a)

In [5]:
l = range(100)
%timeit [i**2 for i in l]

9.96 µs ± 862 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [6]:
a = np.arange(100)
%timeit a**2

944 ns ± 54.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Creating Array

In [9]:
a = np.array([1,2,3,4]) # one dimensional array
print(a.ndim)

1


In [11]:
b = np.array([[1,2,3],[4,5,6]]) # two dimensional array
print(b.ndim)

2


In [13]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # multi dimensional array
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
print(a.shape) #vector

(4,)


In [15]:
print(b.shape) # matrix

(2, 3)


In [16]:
print(c.shape) # cube

(2, 2, 2)


# Functions for creating an Array

In [18]:
a = np.array(10) 
print(a)

10


In [20]:
a = np.arange(1,10,2) 
print(a)

[1 3 5 7 9]


In [21]:
#using linspace
a = np.linspace(0,1,5)
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [22]:
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
a = np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
a = np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [30]:
print(np.diag(a))

[1 2 3 4]


 # Basic Data Types

In [31]:
a = np.arange(10)
print(a.dtype)

int32


In [35]:
a = np.arange(10,dtype="float")
print(a.dtype)

float64


In [36]:
a = np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# Other Datatypes

In [37]:
a = np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [38]:
a = np.array([True,False])
print(a.dtype)

bool


In [40]:
a = np.array(["vamsi","computer"])
print(a.dtype) #unicode string type

<U8


# Indexing and Sclicing

In [42]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [43]:
a = np.arange(10)
print(a[5])

5


In [44]:
a = np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [45]:
a = np.diag([1,2,3])
print(a[2,2])

3


In [46]:
a[2,1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# Slicing

In [47]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
print(a[1:8:2])

[1 3 5 7]


In [49]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [50]:
a = np.arange(10)
a[5:8] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10,  8,  9])

# Copies and Viewing

In [51]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [52]:
print(np.shares_memory(a,b))

True


In [53]:
b[0] = 10
print(a)
print(b) # to confirm share memory

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [54]:
a = np.arange(10)
b = a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [55]:
print(np.shares_memory(a,b))

False


In [56]:
b[0] = 10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random number Generator

In [57]:
a = np.random.randint(0,20,15)
print(a)

[15  1 18 17  4  3  0 10  8  7  4 15 17 16 17]


In [58]:
mask = (a%2==0)

In [59]:
mask_a = a[mask]
print(mask_a)

[18  4  0 10  8  4 16]


In [60]:
a[mask] = -1
print(a)

[15  1 -1 17 -1  3 -1 -1 -1  7 -1 15 17 -1 17]


# Element wise Operations

## 1. Basic Operations

In [2]:
import numpy as np
a = np.array([1,2,3,4])
print(a+1) #addd + 1

[2 3 4 5]


In [3]:
print(a**2) # squares

[ 1  4  9 16]


## All Arthimetic Operates Element wise

In [4]:
b = np.ones(4) + 1
print("a = ",a)
print("b = ",b)

a =  [1 2 3 4]
b =  [2. 2. 2. 2.]


In [5]:
print(a*b)

[2. 4. 6. 8.]


In [6]:
print(a-b)

[-1.  0.  1.  2.]


In [7]:
print(a+b)

[3. 4. 5. 6.]


In [8]:
#Matrix multiplication
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [9]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


## Comparision Operators

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,2,3,4])
print(a==b)

[False  True  True  True]


In [11]:
print(a>b)

[False False False False]


In [12]:
print(a<b)

[ True False False False]


In [13]:
print(a<=b)

[ True  True  True  True]


In [14]:
print(a>=b)

[False  True  True  True]


In [15]:
#Array wise comparision
a = np.array([1,2,3,4])
b = np.array([5,4,1,2])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [16]:
print(np.array_equal(a,c))

True


## Logical  Operators

In [22]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,0,1,0],dtype = "bool")

In [23]:
print(np.logical_or(a,b))

[ True False  True False]


In [24]:
print(np.logical_and(a,b))

[ True False  True False]


In [25]:
print(np.logical_not(a))

[False  True False  True]


## Trigonometry/Transcendental Functions

In [26]:
a = np.array([1,2,3,4])
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [27]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [28]:
print(np.tan(a))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [29]:
print(np.log(a))

[0.         0.69314718 1.09861229 1.38629436]


In [31]:
print(np.exp(a))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


## Basic Reductions

In [32]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [33]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [36]:
a.sum(axis=0)

array([4, 6])

In [37]:
a.sum(axis=1)

array([3, 7])